name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        include:
          - elixir: "1.10.x"
            otp: "22.x"
          - elixir: "1.10.x"
            otp: "23.x"
          - elixir: "1.11.x"
            otp: "22.x"
          - elixir: "1.11.x"
            otp: "23.x"
          - elixir: "1.11.x"
            otp: "24.x"
          - elixir: "1.12.x"
            otp: "22.x"
          - elixir: "1.12.x"
            otp: "23.x"
          - elixir: "1.12.x"
            otp: "24.x"
          - elixir: "1.13.x"
            otp: "22.x"
          - elixir: "1.13.x"
            otp: "23.x"
          - elixir: "1.13.x"
            otp: "24.x"
          - elixir: "1.13.x"
            otp: "25.x"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      # Used to build prettier_eex_formatter
      # Versions from prettier_eex_formatter/.tools_versions
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "22.3.4.26"
          elixir-version: "1.10.4"

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: MIX_ENV=prod cd prettier_eex_formatter && mix compile
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Test Elixir integration
        run: |
          cd tests_elixir
          elixir --version
          mix prettier
